{% set version = "0.3.6.4" %}
{% set postf1 = "" %}
{% set postf2 = "" %}
{% set pandoc = "2.9.2.1" %}
{% set pandoc0 = "2_9_2_1" %}
{% set pandoc1 = "2.10" %}

package:
  name: pandoc-crossref
  version: {{ version }}{{ postf1 }}

source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/pandoc-crossref-Linux-{{ pandoc }}.tar.xz  # [linux64]
  sha256: 57e8f71d46c401daf0a3247b7405b49503b836e93893730e6e5907f6cb2c0885  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/pandoc-crossref-macOS-{{ pandoc }}.tar.xz  # [osx]
  sha256: b63ac830d7164279eb80041cd5f793e6b611ce1a701a86308ce5b2a3a99d33b2  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/pandoc-crossref-Windows-{{ pandoc }}.7z  # [win]
  sha256: 3e943fcdd3f91951fe18f9900e136ccb9ea810b2582f4bd929760357eaf83ef4  # [win]

build:
   number: 0

requirements:
  run:
    - pandoc >={{ pandoc }},<{{ pandoc1 }}

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Pandoc filter for cross-references'
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://github.com/lierdakil/pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
