{% set version = "0.3.6.1" %}
{% set postf1 = ".1" %}
{% set postf2 = "a" %}
{% set pandoc = "2.9" %}
{% set pandoc0 = "2_9" %}
{% set pandoc1 = "2.10" %}

package:
  name: pandoc-crossref
  version: {{ version }}{{ postf1 }}

source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/linux-pandoc_{{ pandoc0 }}.tar.gz  # [linux64]
  sha256: 1346a31f6ccf53d198986cf06a7e583e5a8e5026be0deb6f2b24c5423f8e2453  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/macos-pandoc_{{ pandoc0 }}.tar.gz  # [osx]
  sha256: d1160222971fa00a209bbbf8a6d4e1c6213940859164598b496ac0f4045a8938  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/windows-x86_64-pandoc_{{ pandoc }}.zip  # [win]
  sha256: f2d6e2a1ffd21c567363c00cc7e0413e6e74a76909ae71576c43b9b72c188a87  # [win]

build:
   number: 0

requirements:
  run:
    - pandoc >={{ pandoc }},<{{ pandoc1 }}

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Pandoc filter for cross-references'
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://github.com/lierdakil/pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
