{% set version = "0.3.6.2" %}
{% set postf1 = "" %}
{% set postf2 = "" %}
{% set pandoc = "2.9.2" %}
{% set pandoc1 = "2.10" %}

package:
  name: pandoc-crossref
  version: {{ version }}{{ postf1 }}

source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/linux-pandoc_2_9_2.tar.gz  # [linux64]
  sha256: 8f14297487b55ecf4ce79eed8b99999198b6cf930cfeab693be7cee260a0fe43  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/macos-pandoc_2_9_2.tar.gz  # [osx]
  sha256: 73b90a78ff0515788eca438345f84590c4555493936a67465bd108a7edd1c6b5  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/windows-x86_64-pandoc_{{ pandoc }}.zip  # [win]
  sha256: 75ac5da714fae4b41aef5c4767f7a6dcec5373ad7928483738044150f41226de  # [win]

build:
   number: 0

requirements:
  run:
    - pandoc >={{ pandoc }},<{{ pandoc1 }}

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref
  license: GPL-2.0-only
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: Pandoc filter for cross-references
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://github.com/lierdakil/pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
