{% set version = "0.3.10.0" %}
{% set postf1 = "" %}
{% set postf2 = "" %}
{% set pandoc = "2.11" %}
{% set pandoc1 = "2.13" %}

package:
  name: pandoc-crossref
  version: {{ version }}{{ postf1 }}

source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/pandoc-crossref-Linux.tar.xz  # [linux64]
  sha256: c851cc8da8cb654207f7a26fab03562938db1830b78db60feb20e663d9a354a9  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/pandoc-crossref-macOS.tar.xz  # [osx]
  sha256: 9db71ad991097004391cf1414603e21888d5bff5c774bea9a30a4b027c557912  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/pandoc-crossref-Windows.7z  # [win]
  sha256: b6a5fd7de26258c2ed451f8c46fa52f14b8ab7102a44f699232a4cd18582de5d  # [win]

build:
  number: 1

requirements:
  run:
    - pandoc >={{ pandoc }},<{{ pandoc1 }}

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref
  license: GPL-2.0-only
  license_family: GPL
  license_file: {{ environ["RECIPE_DIR"] }}/LICENSE
  summary: Pandoc filter for cross-references
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://github.com/lierdakil/pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
    - mfansler
