{% set version = "0.3.6.1" %}
{% set pandoc = "2.9" %}
{% set pandoc0 = "2_9" %}
{% set pandoc1 = "2.10" %}

package:
  name: pandoc-crossref
  version: {{ version }}

source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}/linux-pandoc_{{ pandoc0 }}.tar.gz  # [linux64]
  sha256: 066997a4e6df1775f3081c6c004d3811506e4de9f3f7201f4b31f6b7fd454f92  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}/macos-pandoc_{{ pandoc0 }}.tar.gz  # [osx]
  sha256: b3fa48c64a87f55c8bf03df6887704fc5fae4a1cb80831c5431601bd6fb4f06b  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}/windows-x86_64-pandoc_{{ pandoc }}.zip  # [win]
  sha256: 0d91851b699c64ceb742f8d49c3ab68974ecd327a1ba49637b32eec6c482677e  # [win]

build:
   number: 0

requirements:
  run:
    - pandoc >={{ pandoc }},<{{ pandoc1 }}

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Pandoc filter for cross-references'
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://github.com/lierdakil/pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
