{% set version = "0.3.5.0.1" %}

{% set crossref_ver = "0.3.5.0a" %}
{% set pandoc_unix_ver = "2_8_0_1" %}
{% set pandoc_win_ver = "2.8.0.1" %}

package:
  name: pandoc-crossref
  version: {{ version }}

source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ crossref_ver }}/linux-pandoc_{{ pandoc_unix_ver }}.tar.gz  # [linux64]
  sha256: cb8c52e53a60a34cdb1114b9597c5195c714631948b2b05e5f8eea2431eea471  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ crossref_ver }}/macos-pandoc_{{ pandoc_unix_ver }}.tar.gz  # [osx]
  sha256: d595aae5957777c5ba82e7b3019868e8b6aeb6b9153da12a30f9683ea1a6eb92  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ crossref_ver }}/windows-x86_64-pandoc_{{ pandoc_win_ver }}.zip  # [win]
  sha256: 894886da621f80d7a6f4823d75b47bf93999d797dad0df3f226f0dcf3d71975d  # [win]

build:
   number: 0

requirements:
  run:
    - pandoc >=2.8.0.1,<2.9

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Pandoc filter for cross-references'
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://github.com/lierdakil/pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
