{% set version = "0.3.6.1" %}
{% set postf1 = ".2" %}
{% set postf2 = "b" %}
{% set pandoc = "2.9.1.1" %}
{% set pandoc0 = "2_9_1_1" %}
{% set pandoc1 = "2.10" %}

package:
  name: pandoc-crossref
  version: {{ version }}{{ postf1 }}

source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/linux-pandoc_{{ pandoc0 }}.tar.gz  # [linux64]
  sha256: c3781d8468fc22a0397232089b563fc8d132b3368f0d57abd5bb020faefebbd3  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/macos-pandoc_{{ pandoc0 }}.tar.gz  # [osx]
  sha256: 6ad2b8913b274a4db9a0ee5d1d744c85c08f9b3255c57d8f3b7d128bfe048db4  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ postf2 }}/windows-x86_64-pandoc_{{ pandoc }}.zip  # [win]
  sha256: 29e242ffb7673eeeff533db3ba943ed674cfd6429d1eaf755994b4dd2505fdc5  # [win]

build:
   number: 0

requirements:
  run:
    - pandoc >={{ pandoc }},<{{ pandoc1 }}

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Pandoc filter for cross-references'
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://github.com/lierdakil/pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
