{% set version = "0.3.4.2" %}

{% set crossref_ver = "0.3.4.2" %}
{% set pandoc_unix_ver = "2_7_3" %}
{% set pandoc_win_ver = "2.7.3" %}

package:
  name: pandoc-crossref
  version: {{ version }}

source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ crossref_ver }}/linux-pandoc_{{ pandoc_unix_ver }}.tar.gz  # [linux64]
  sha256: 959dd9b5591849241d2c63314607d2ef2590ca76dd01b7c8823284c50a61f52e  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ crossref_ver }}/macos-pandoc_{{ pandoc_unix_ver }}.tar.gz  # [osx]
  sha256: d5bc90b1ef3f2e5ca8468dcaaeb6b526bdc3d8f1f9faa1332ddd42f0a3f5eb3f  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ crossref_ver }}/windows-x86_64-pandoc_{{ pandoc_win_ver }}.zip  # [win]
  sha256: 5227ee626df97c7f06336697851aedbd114ea914d4d20988ec9c3dd07f69413b  # [win]

build:
   number: 2

requirements:
  run:
    - pandoc >=2.7.3,<2.8

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Pandoc filter for cross-references'
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://github.com/lierdakil/pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
