{% set version = "0.3.12.0" %}
# this appears in version but not in url
{% set version_part = "" %}
# see https://github.com/lierdakil/pandoc-crossref/issues/311#issuecomment-844626176 for why there's a hidden part not normally seen in the version
{% set version_hidden_part = "e" %}
# best place to check the version constraint is https://hackage.haskell.org/package/pandoc-crossref
{% set pandoc_min_version = "2.10" %}
{% set pandoc_max_version = "2.17" %}

package:
  name: pandoc-crossref
  version: {{ version }}{{ version_part }}

# you may use VERSION=... sha256sum.sh to produce the following checksum
source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-Linux.tar.xz  # [linux64]
  sha256: bc451e8ce7b0a99d1effa48140a263695f7e845b37899e3f40b56b26f51b013d  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-macOS.tar.xz  # [osx]
  sha256: 14341719ce2cb15a4c98a94227f8d6040a16bdb0ab1495192671831e6bde3cbe  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ version }}{{ version_hidden_part }}/pandoc-crossref-Windows.7z  # [win]
  sha256: 23a5bf504402a2f511348efc90b89f1ae57c05c9d568c60b74e59eef3110aa3a  # [win]

build:
  number: 3

requirements:
  run:
    - pandoc >={{ pandoc_min_version }},<{{ pandoc_max_version }}

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref/
  # see https://github.com/lierdakil/pandoc-crossref#license
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE
  summary: Pandoc filter for cross-references
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://hackage.haskell.org/package/pandoc-crossref/

extra:
  recipe-maintainers:
    - kiwi0fruit
    - mfansler
    - knaaptime
    - ickc
