{% set version = "0.3.5.0" %}

{% set crossref_ver = "0.3.5.0" %}
{% set pandoc_unix_ver = "2_8" %}
{% set pandoc_win_ver = "2.8" %}

package:
  name: pandoc-crossref
  version: {{ version }}

source:
  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ crossref_ver }}/linux-pandoc_{{ pandoc_unix_ver }}.tar.gz  # [linux64]
  sha256: e7747a09bfc13222278140045f28041975ccfb804f5462a981c907832a31a0af  # [linux64]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ crossref_ver }}/macos-pandoc_{{ pandoc_unix_ver }}.tar.gz  # [osx]
  sha256: ac81d9d3223800b482bda5c14ef04331b5c6f2c9c4b77dd2d70ca8d68d102bfa  # [osx]

  url: https://github.com/lierdakil/pandoc-crossref/releases/download/v{{ crossref_ver }}/windows-x86_64-pandoc_{{ pandoc_win_ver }}.zip  # [win]
  sha256: 9a660db7e38cf0972418cd9d20278008b98c33b79ad13c12c0bf134321df391a  # [win]

build:
   number: 0

requirements:
  run:
    - pandoc >=2.8,<2.9

test:
  commands:
    - pandoc-crossref --help
    - pandoc-crossref --version

about:
  home: https://github.com/lierdakil/pandoc-crossref
  license: GPL-2.0
  license_family: GPL
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE'
  summary: 'Pandoc filter for cross-references'
  doc_url: https://lierdakil.github.io/pandoc-crossref/
  dev_url: https://github.com/lierdakil/pandoc-crossref

extra:
  recipe-maintainers:
    - kiwi0fruit
