travis:
  secure:
    BINSTAR_TOKEN: m04rvuKt2jzYWd+1VOvdtG9f1MPK4Z/5jtdY/arLyVdohZFnU8paGqi2f96nw4Sbq0SJGS4oevNNjESIloaYS3Upz5ta9tB/EyqsIhfQ4SchkbJQdjtqSo6nmqPfYfAfOLveK4z1AdSWX781K0WKr7VdidVR/+fwwrBAASdKX1q0vIz5n/7Pi8ou3s2XvsieKT4yWe+ldBqtcbtSg3EXytwSgXUrcSv+t1V4ATg15wlrv7LYpYhsVqDq/TH/H57Jc6CqNd19dakDBTJvtLvwzSqb3ipgwiA6STar3o2CJ8SOuOrSYdlx3iLxoB3cjKludraRWbIc+l6j2q38Tc/dt4T/awscuodfkhn6UJzRhTghrjhAUdqBKGBtZ6ONigEGlhjC2UeXnAfIL6fRJuos3s/J/P/qeBz2RRdbphh/K3J4hGBjDCz0mBG1UD1um7oZGPTyMmk34IUwgQ4KgjqAdA8+NfVro8v71hVfP6pmAzAuFTl+LryCm8vTXXaIHpYaLQDcRPzMlb+KXygUdCi7eq7U4KrL72RIhOt0eTrL1/4wTL61pXWNPB9ZAuJB6rJi3X1PHgSsqd3QBQrxEpTDi8ryWHo0qK5MGG9UQq6mr0ab248s6ak+z2ly+mqRflD4oK1E/XOO0+Rg/H56IkJmVHV+reHSb+M3xva7+LwkSa4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
conda_forge_output_validation: true
